name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install pandoc and make
        run: sudo apt install pandoc make --yes
        
      - name: Install XSLTProc
        run: sudo apt install xsltproc
        
      - name: One Make to Rule them all
        run: make all

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
          git-config-user: "gh-runner"
          git-config-email: "gh@example.com"
